# This file is used to configure the Render service for the HealthSavvy application.
services:
  - type: web
    name: healthsavvy
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=1 --threads=4 --timeout=60 --memory-limit=512 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false